from app.api.routes import (
    agencias,
    auth,
    cargos,
    departamentos,
    empresas,
    eventos,
    health,
    root,
    sessoes_trabalho,
    status,
    usuario_cargos,
    usuario_departamentos,
    usuarios,
)

__all__ = [
    "agencias",
    "auth",
    "cargos",
    "departamentos",
    "empresas",
    "eventos",
    "health",
    "root",
    "sessoes_trabalho",
    "status",
    "usuario_cargos",
    "usuario_departamentos",
    "usuarios",
]
