from app.api.routes import (
    agencias,
    auth,
    cargos,
    clientes,
    departamentos,
    equipes,
    empresas,
    eventos,
    health,
    root,
    sessoes_trabalho,
    status,
    usuario_cargos,
    usuario_departamentos,
    usuario_equipes,
    usuarios,
)

__all__ = [
    "agencias",
    "auth",
    "cargos",
    "clientes",
    "departamentos",
    "equipes",
    "empresas",
    "eventos",
    "health",
    "root",
    "sessoes_trabalho",
    "status",
    "usuario_cargos",
    "usuario_departamentos",
    "usuario_equipes",
    "usuarios",
]
