"""schema fase 1

Revision ID: f9424ecbc81c
Revises:
Create Date: 2026-08-03 14:37:12.942042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9424ecbc81c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('documento', sa.String(length=32), nullable=True),
    sa.Column('codigo_interno', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inativado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inativado_por_usuario_id', sa.String(length=128), nullable=True),
    sa.Column('motivo_inativacao', sa.String(length=500), nullable=True),
    sa.CheckConstraint("status IN ('ativa', 'inativa', 'arquivada')", name='ck_empresas_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno', name='uq_empresas_codigo_interno'),
    sa.UniqueConstraint('documento', name='uq_empresas_documento')
    )
    op.create_index('ix_empresas_created_at', 'empresas', ['created_at'], unique=False)
    op.create_index('ix_empresas_status', 'empresas', ['status'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=128), nullable=False),
    sa.Column('agencia_id', sa.String(length=128), nullable=True),
    sa.Column('tipo', sa.String(length=128), nullable=False),
    sa.Column('entidade_tipo', sa.String(length=128), nullable=False),
    sa.Column('entidade_id', sa.String(length=128), nullable=False),
    sa.Column('usuario_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('causation_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eventos_correlation_id', 'eventos', ['correlation_id'], unique=False)
    op.create_index('ix_eventos_empresa_id', 'eventos', ['empresa_id'], unique=False)
    op.create_index('ix_eventos_entidade', 'eventos', ['entidade_tipo', 'entidade_id'], unique=False)
    op.create_index('ix_eventos_occurred_at', 'eventos', ['occurred_at'], unique=False)
    op.create_index('ix_eventos_tipo', 'eventos', ['tipo'], unique=False)
    op.create_table('sessoes_trabalho',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=128), nullable=False),
    sa.Column('agencia_id', sa.String(length=128), nullable=True),
    sa.Column('demanda_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_etapa_id', sa.String(length=128), nullable=True),
    sa.Column('usuario_id', sa.String(length=128), nullable=True),
    sa.Column('departamento_id', sa.String(length=128), nullable=True),
    sa.Column('evento_inicio_id', sa.String(length=36), nullable=False),
    sa.Column('evento_fim_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('inicio_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracao_segundos', sa.Integer(), nullable=True),
    sa.Column('motivo_encerramento', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status != 'ativa' OR (fim_em IS NULL AND evento_fim_id IS NULL AND duracao_segundos IS NULL)", name='ck_sessoes_trabalho_ativa_sem_fim'),
    sa.CheckConstraint("status != 'encerrada' OR (fim_em IS NOT NULL AND evento_fim_id IS NOT NULL AND duracao_segundos IS NOT NULL)", name='ck_sessoes_trabalho_encerrada_com_fim'),
    sa.CheckConstraint("status IN ('ativa', 'encerrada', 'cancelada')", name='ck_sessoes_trabalho_status'),
    sa.CheckConstraint('duracao_segundos IS NULL OR duracao_segundos >= 0', name='ck_sessoes_trabalho_duracao_nao_negativa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessoes_trabalho_demanda_id', 'sessoes_trabalho', ['demanda_id'], unique=False)
    op.create_index('ix_sessoes_trabalho_departamento_id', 'sessoes_trabalho', ['departamento_id'], unique=False)
    op.create_index('ix_sessoes_trabalho_empresa_id', 'sessoes_trabalho', ['empresa_id'], unique=False)
    op.create_index('ix_sessoes_trabalho_evento_fim_id', 'sessoes_trabalho', ['evento_fim_id'], unique=False)
    op.create_index('ix_sessoes_trabalho_evento_inicio_id', 'sessoes_trabalho', ['evento_inicio_id'], unique=True)
    op.create_index('ix_sessoes_trabalho_inicio_em', 'sessoes_trabalho', ['inicio_em'], unique=False)
    op.create_index('ix_sessoes_trabalho_status', 'sessoes_trabalho', ['status'], unique=False)
    op.create_index('ix_sessoes_trabalho_usuario_id', 'sessoes_trabalho', ['usuario_id'], unique=False)
    op.create_index('ix_sessoes_trabalho_workflow_etapa_id', 'sessoes_trabalho', ['workflow_etapa_id'], unique=False)
    op.create_index('uq_sessoes_trabalho_ativa_demanda_departamento', 'sessoes_trabalho', ['demanda_id', 'departamento_id'], unique=True, postgresql_where=sa.text("usuario_id IS NULL AND departamento_id IS NOT NULL AND status = 'ativa'"), sqlite_where=sa.text("usuario_id IS NULL AND departamento_id IS NOT NULL AND status = 'ativa'"))
    op.create_index('uq_sessoes_trabalho_ativa_demanda_usuario', 'sessoes_trabalho', ['demanda_id', 'usuario_id'], unique=True, postgresql_where=sa.text("usuario_id IS NOT NULL AND status = 'ativa'"), sqlite_where=sa.text("usuario_id IS NOT NULL AND status = 'ativa'"))
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('codigo_interno', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('perfil_base', sa.String(length=32), nullable=False),
    sa.Column('acesso_sistema', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('telefone', sa.String(length=32), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('bairro', sa.String(length=255), nullable=True),
    sa.Column('endereco_completo', sa.String(length=500), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('contatos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('departamento_id', sa.String(length=64), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('lider_departamento', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('valor_recebido_mensal_centavos', sa.Integer(), nullable=True),
    sa.Column('horas_trabalho_aproximadas', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('cor_identificacao', sa.String(length=32), nullable=True),
    sa.Column('is_system_account', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inativado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inativado_por_usuario_id', sa.String(length=36), nullable=True),
    sa.Column('motivo_inativacao', sa.String(length=500), nullable=True),
    sa.CheckConstraint("perfil_base IN ('admin', 'gestor', 'operador')", name='ck_usuarios_perfil_base'),
    sa.CheckConstraint("status IN ('ativo', 'inativo', 'bloqueado', 'arquivado')", name='ck_usuarios_status'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['inativado_por_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_interno', name='uq_usuarios_empresa_codigo_interno'),
    sa.UniqueConstraint('empresa_id', 'email', name='uq_usuarios_empresa_email')
    )
    op.create_index('ix_usuarios_created_at', 'usuarios', ['created_at'], unique=False)
    op.create_index('ix_usuarios_empresa_id', 'usuarios', ['empresa_id'], unique=False)
    op.create_index('ix_usuarios_is_system_account', 'usuarios', ['is_system_account'], unique=False)
    op.create_index('ix_usuarios_perfil_base', 'usuarios', ['perfil_base'], unique=False)
    op.create_index('ix_usuarios_status', 'usuarios', ['status'], unique=False)
    op.create_table('usuario_credenciais',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('senha_definida_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('senha_alterada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentativas_falhas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('senha_deve_ser_alterada', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', name='uq_usuario_credenciais_usuario_id')
    )
    op.create_index('ix_usuario_credenciais_created_at', 'usuario_credenciais', ['created_at'], unique=False)
    op.create_index('ix_usuario_credenciais_usuario_id', 'usuario_credenciais', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuario_credenciais_usuario_id', table_name='usuario_credenciais')
    op.drop_index('ix_usuario_credenciais_created_at', table_name='usuario_credenciais')
    op.drop_table('usuario_credenciais')
    op.drop_index('ix_usuarios_status', table_name='usuarios')
    op.drop_index('ix_usuarios_perfil_base', table_name='usuarios')
    op.drop_index('ix_usuarios_is_system_account', table_name='usuarios')
    op.drop_index('ix_usuarios_empresa_id', table_name='usuarios')
    op.drop_index('ix_usuarios_created_at', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('uq_sessoes_trabalho_ativa_demanda_usuario', table_name='sessoes_trabalho', postgresql_where=sa.text("usuario_id IS NOT NULL AND status = 'ativa'"), sqlite_where=sa.text("usuario_id IS NOT NULL AND status = 'ativa'"))
    op.drop_index('uq_sessoes_trabalho_ativa_demanda_departamento', table_name='sessoes_trabalho', postgresql_where=sa.text("usuario_id IS NULL AND departamento_id IS NOT NULL AND status = 'ativa'"), sqlite_where=sa.text("usuario_id IS NULL AND departamento_id IS NOT NULL AND status = 'ativa'"))
    op.drop_index('ix_sessoes_trabalho_workflow_etapa_id', table_name='sessoes_trabalho')
    op.drop_index('ix_sessoes_trabalho_usuario_id', table_name='sessoes_trabalho')
    op.drop_index('ix_sessoes_trabalho_status', table_name='sessoes_trabalho')
    op.drop_index('ix_sessoes_trabalho_inicio_em', table_name='sessoes_trabalho')
    op.drop_index('ix_sessoes_trabalho_evento_inicio_id', table_name='sessoes_trabalho')
    op.drop_index('ix_sessoes_trabalho_evento_fim_id', table_name='sessoes_trabalho')
    op.drop_index('ix_sessoes_trabalho_empresa_id', table_name='sessoes_trabalho')
    op.drop_index('ix_sessoes_trabalho_departamento_id', table_name='sessoes_trabalho')
    op.drop_index('ix_sessoes_trabalho_demanda_id', table_name='sessoes_trabalho')
    op.drop_table('sessoes_trabalho')
    op.drop_index('ix_eventos_tipo', table_name='eventos')
    op.drop_index('ix_eventos_occurred_at', table_name='eventos')
    op.drop_index('ix_eventos_entidade', table_name='eventos')
    op.drop_index('ix_eventos_empresa_id', table_name='eventos')
    op.drop_index('ix_eventos_correlation_id', table_name='eventos')
    op.drop_table('eventos')
    op.drop_index('ix_empresas_status', table_name='empresas')
    op.drop_index('ix_empresas_created_at', table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
