"""usuario_arquivamento

Revision ID: 76f7f6fb4a70
Revises: f9424ecbc81c
Create Date: 2026-08-04 13:05:01.607246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f7f6fb4a70'
down_revision: Union[str, None] = 'f9424ecbc81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('arquivado_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('arquivado_por_usuario_id', sa.String(length=36), nullable=True))
    op.add_column('usuarios', sa.Column('motivo_arquivamento', sa.String(length=500), nullable=True))
    op.add_column('usuarios', sa.Column('restaurado_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('restaurado_por_usuario_id', sa.String(length=36), nullable=True))
    op.add_column('usuarios', sa.Column('status_anterior_arquivamento', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'status_anterior_arquivamento')
    op.drop_column('usuarios', 'restaurado_por_usuario_id')
    op.drop_column('usuarios', 'restaurado_at')
    op.drop_column('usuarios', 'motivo_arquivamento')
    op.drop_column('usuarios', 'arquivado_por_usuario_id')
    op.drop_column('usuarios', 'arquivado_at')
    # ### end Alembic commands ###
