import type { AgendaContato } from "@/types/agenda";

export const agendaMock: AgendaContato[] = [
  {
    id: "agenda-1",
    tipo: "clientes",
    nome: "Casa Brasil",
    empresa: "Casa Brasil",
    cargo: "Diretora de Marketing",
    departamento: "Marketing",
    email: "contato@casabrasil.mock",
    telefone: "(11) 3333-1000",
    celular: "(11) 98888-1000",
    favorito: true,
    ultimaInteracao: "2026-07-05T09:30:00-03:00",
    avatarUrl: null,
    avatarThumbnail: null,
  },
  {
    id: "agenda-2",
    tipo: "clientes",
    nome: "Clínica Clare",
    empresa: "Clínica Clare",
    cargo: "Gerente Comercial",
    departamento: "Comercial",
    email: "comercial@clinicaclare.mock",
    telefone: "(11) 3333-2000",
    celular: "(11) 98888-2000",
    favorito: false,
    ultimaInteracao: "2026-07-04T14:10:00-03:00",
    avatarUrl: null,
    avatarThumbnail: null,
  },
  {
    id: "agenda-3",
    tipo: "clientes",
    nome: "Grupo Horizonte",
    empresa: "Grupo Horizonte",
    cargo: "Head de Operações",
    departamento: "Operações",
    email: "operacoes@grupohorizonte.mock",
    telefone: "(11) 3333-3000",
    celular: "(11) 98888-3000",
    favorito: false,
    ultimaInteracao: "2026-07-03T18:20:00-03:00",
    avatarUrl: null,
    avatarThumbnail: null,
  },
  {
    id: "agenda-4",
    tipo: "fornecedores",
    nome: "Gráfica Alpha",
    empresa: "Gráfica Alpha",
    cargo: "Executivo de Conta",
    departamento: "Atendimento",
    email: "atendimento@graficaalpha.mock",
    telefone: "(11) 3333-4000",
    celular: "(11) 98888-4000",
    favorito: true,
    ultimaInteracao: "2026-07-06T11:05:00-03:00",
    avatarUrl: null,
    avatarThumbnail: null,
  },
  {
    id: "agenda-5",
    tipo: "fornecedores",
    nome: "Studio Motion",
    empresa: "Studio Motion",
    cargo: "Produtor",
    departamento: "Produção",
    email: "contato@studiomotion.mock",
    telefone: "(11) 3333-5000",
    celular: "(11) 98888-5000",
    favorito: false,
    ultimaInteracao: "2026-07-01T16:00:00-03:00",
    avatarUrl: null,
    avatarThumbnail: null,
  },
  {
    id: "agenda-6",
    tipo: "usuarios",
    nome: "Administrador TaskFloww",
    empresa: "TaskFloww",
    cargo: "Administrador",
    departamento: "Operações",
    email: "admin@taskfloww.local",
    telefone: "(11) 3333-6000",
    celular: "(11) 98888-6000",
    favorito: false,
    ultimaInteracao: "2026-07-06T08:50:00-03:00",
    avatarUrl: null,
    avatarThumbnail: null,
  },
  {
    id: "agenda-7",
    tipo: "usuarios",
    nome: "Analista Operações",
    empresa: "TaskFloww",
    cargo: "Analista",
    departamento: "Criação",
    email: "operacoes@taskfloww.local",
    telefone: "(11) 3333-7000",
    celular: "(11) 98888-7000",
    favorito: false,
    ultimaInteracao: "2026-07-02T13:15:00-03:00",
    avatarUrl: null,
    avatarThumbnail: null,
  },
];
